### ISSUE TITLE
Hotkeys selection is unavailable

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#34]
"**Environment:**
Win 11 
Eudora 1.0.20.0

**Precondition:**
Eudora 1.0.20.0 should be opened
Setting should be opened

**STR:**
1.Click on "Hotkeys" selection

**Actual Result:**
Hotkeys selection is unavailable

**Expected Result:**
It should be available

**Attachments:**"
![image](https://github.com/user-attachments/assets/365e2c74-204d-4f10-8b66-ce09f453b0ab)

**Comment by ispeedonthe405** [comment]
I haven't yet had time to make those features real.

Hotkeys tab
I added that tab and the idea behind it as a result of my own user experience. Eudora.Net is now big and complex enough that we should expect daily users to develop their own routine flows and mechanical interactions with the software. It occurred to me that we should feature assignable hotkeys for all kinds of things: bind a hotkey to open up a particular inbox, or to create a new draft with a certain sender account selected, or addressed to a particular recipient; stuff like that.


For 1.0.22 I'll hide the tab instead of just disabling it.
