### ISSUE TITLE
"Storage" selection is unavailable

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#35]
"Environment:
Win 11
Eudora 1.0.20.0

Precondition:
Eudora 1.0.20.0 should be opened
Setting should be opened

STR:
1.Click on "Storage" selection

Actual Result:
"Storage" selection is unavailable

Expected Result:
It should be available

Attachments:"
![image](https://github.com/user-attachments/assets/c2f522b3-0eb4-46c1-b205-9ab4efa5519a)

**Comment by ispeedonthe405** [comment]
I haven't yet had time to make those features real.

Storage tab
Gives you the ability to change your mind about where Eudora.Net keeps its datastore. This also requires foolproof & secure data migration when the user does change the folder/location.

Hotkeys tab
I added that tab and the idea behind it as a result of my own user experience. Eudora.Net is now big and complex enough that we should expect daily users to develop their own routine flows and mechanical interactions with the software. It occurred to me that we should feature assignable hotkeys for all kinds of things: bind a hotkey to open up a particular inbox, or to create a new draft with a certain sender account selected, or addressed to a particular recipient; stuff like that.

Sadly, I haven't yet had time to actually do any of that. That's why the tabs are disabled.

For 1.0.22 I'll hide them instead of just disabling them.
