### ISSUE TITLE
User can create 2 mailboxes with same names 

### ISSUE THREAD

**Issue by Romankfdk** [agilenature/Eudora.Net#42]
![image](https://github.com/user-attachments/assets/f0cb870e-bf6c-4324-8d0c-139711cab1d6)

**Comment by ispeedonthe405** [comment]
I know that seems weird, but it's by design. 

It's possible that a user might import mailboxes from old Eudora that will have the same name as an existing box, but should be kept separate instead of merging into another that happens to have the same name. It's also possible that they might create, for example, multiple new boxes with the same name; each for a different account, or workflow, or however they're thinking.

To support those edge cases, the name of a mailbox is not the unique field (i.e primary key). Instead, the PK is a unique identifier, a GUID, that the user doesn't see. Even though two boxes might have the same name, there is no collision or confusion.
